# Generated by Django 4.0 on 2024-09-08 15:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='foydalanuvchi ismi')),
                ('email', models.EmailField(max_length=200, verbose_name='foydalanuvchi emaili')),
                ('topic', models.CharField(max_length=100, verbose_name='mavzu')),
                ('message', ckeditor.fields.RichTextField(verbose_name='foydalanuvchi xabari')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Loyiha haqida malumot')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='blog nomi')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('text', ckeditor.fields.RichTextField(verbose_name='blog haqida malumot')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
